function buat_login(){
  var element = document.getElementById("x");
  element.parentElement.removeChild(element);
  var paragraph = document.createElement("p");
  paragraph.className = "tulisan_login";
  paragraph.innerHTML = "silahkan mendaftar";
  var elem = document.getElementsByTagName("div")[0];
  elem.appendChild(paragraph);
  var form = document.createElement("form");
  elem.appendChild(form);
  var label_nama = document.createElement("label");
  label_nama.innerHTML = "Nama User";
  elem.appendChild(label_nama);
  var input_nama = document.createElement("input");
  input_nama.type = "text";
  input_nama.name = "name";
  input_nama.className = "form_login";
  input_nama.placeholder = "Nama User..";
  elem.appendChild(input_nama);
  var label_kontak = document.createElement("label");
  label_kontak.innerHTML = "Nomor Handphone";
  elem.appendChild(label_kontak);
  var input_kontak = document.createElement("input");
  input_kontak.type = "tel";
  input_kontak.pattern = "\d";
  input_kontak.name = "contact";
  input_kontak.className = "form_login";
  input_kontak.id = "phone";
  input_kontak.placeholder = "Nomor Handphone..";
  elem.appendChild(input_kontak);
  var label_username = document.createElement("label");
  label_username.innerHTML = "Username";
  elem.appendChild(label_username);
  var input_username = document.createElement("input");
  input_username.type = "text";
  input_username.name = "username";
  input_username.className = "form_login";
  input_username.placeholder = "Username atau email..";
  elem.appendChild(input_username);
  var label_password = document.createElement("label");
  label_password.innerHTML = "Password";
  elem.appendChild(label_password);
  var input_password = document.createElement("input");
  input_password.type = "password";
  input_password.name = "password";
  input_password.className = "form_login";
  input_password.placeholder = "Password..";
  elem.appendChild(input_password);
  var tombol = document.createElement("input");
  tombol.type = "submit";
  tombol.name = "submit";
  tombol.value = "DAFTAR SEKARANG";
  tombol.className="tombol_login"
  elem.appendChild(tombol);
}
